name: Deploy to gh-pages site

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and deploy
      env:
        CI: true
        AIRTABLE_API_SECRET: ${{ secrets.AIRTABLE_API_SECRET }}
      run: |
        npm install
        npm run build
        npm run predeploy
        git config user.email "github_actions@knowit.no"
        git config user.name "GitHub Actions"
        npm run deploy
        
